name: TDD tests with GitHub Actions
on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using npm after installing packages
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
